<?php

use Drupal\block_content\Entity\BlockContent;
use Drupal\block\Entity\Block;
use Drupal\node\Entity\Node;
use Drupal\Core\Url;

// Globals
$GLOBALS["cookie_name"] = 'CookieConsent';

/**
 * Implement hook_theme()
 *
 * This function tells each theme template what variables they can use
 *
 * @param array $existing
 * @param string $type
 * @param string $theme
 * @param string $path
 * @return array
 */
function kees_cookiebar_theme($existing, $type, $theme, $path)
{
    // This defines the variables that will be useable in the templates
    return array(
        'kees_cookiebar' => array(
            'variables' => array(
                'label' => null,
                'cookies' => null,
                'text' => null,
                'accept_button_text' => null,
                'decline_button_text' => null,
            ),
        ),
        'kees_cookiebar_advanced' => array(
            'variables' => array(
                'label' => null,
                'cookies' => null,
                'text' => null,
                'accept_button_text' => null,
                'decline_button_text' => null,
            ),
        ),
    );
}

/**
 * Implement hook_install()
 * Will Add a block to content of current theme when installing the plugin
 *
 * @return void
 */
function kees_cookiebar_install()
{
    // Add block to content on module install
    $cookiebarBlock = Block::create([
        'id' => 'kees_cookiebar_block',
        'plugin' => 'kees_cookiebar_block',
        'region' => 'content',
        'weight' => 99,
        'theme' => \Drupal::config('system.theme')->get('default'),
        'settings' => [
            'label' => 'KeesTM Cookiebar Block',
            'label_display' => false,
        ],
    ]);
    $cookiebarBlock->save();

    // (Re)set saved config. This is sometimes cached in some wierd way...
    $config_file = \file_get_contents(DRUPAL_ROOT . '/' . drupal_get_path('module', 'kees_cookiebar') . "/config/install/kees_cookiebar.settings.yml");
    $parsed = \Symfony\Component\Yaml\Yaml::parse($config_file);
    $config_factory = \Drupal::configFactory();
    $config = $config_factory->getEditable('kees_cookiebar.settings');
    $config->setData($parsed);
    $config->save(true);
}

/**
 * Implement hook_page_attachments
 *
 * This function will attach a stylesheet to all admin pages.
 *
 * @param array $attachments
 * @return void
 */
function kees_cookiebar_page_attachments(array &$attachments)
{
    $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
    if ($is_admin) {
        $attachments['#attached']['library'][] = 'kees_cookiebar/cookiebar-css-admin';
        return;
    }
}

/**
 * Implement hook_preprocess
 *
 * This preprocess will add a variable to all pages
 *
 * @param array $variables
 * @return void
 */
function kees_cookiebar_preprocess(&$variables)
{
    $variables['kees_cookie_value'] = GetCookieValue();
}

/**
 * Implement hook_preprocess_html
 *
 * Add some configuration to the javascript library
 *
 * @param array $variables
 * @return void
 */
function kees_cookiebar_preprocess_html(&$variables)
{
    $config = \Drupal::service('config.factory')->getEditable('kees_cookiebar.settings');
    $cookiepage_path = $config->get('kees_cookiebar.cookiepage_path');
    if (empty($cookiepage_path)) {
        $cookiepage_path = "/cookies";
        $config->set('kees_cookiebar.cookiepage_path', $cookiepage_path);
        $config->save();
    }

    $current_language = Drupal::languageManager()->getCurrentLanguage();
    $default_lang = Drupal::languageManager()->getDefaultLanguage();
    $homeUrl = Url::fromRoute('<front>', [], ['language' => $current_language]);
    $currentUrl = Url::fromRoute('<current>', [], ['language' => $default_lang]);

    $variables['#attached']['drupalSettings']['keesCookiebarConfig'] = array(
        'cookiepagePath' => $cookiepage_path,
        'homeUrl' => $homeUrl->toString(),
        'currentUrl' => $currentUrl->toString(),
    );
}

/**
 * Implement hook_menu_local_tasks_alter
 *
 * Will alter the local tasks based on the cookiebar_type
 *
 * @param array $data
 * @param string $route_name
 * @return void
 */
function kees_cookiebar_menu_local_tasks_alter(&$data, $route_name)
{
    $config = \Drupal::config('kees_cookiebar.settings');
    $cookiebar_type = $config->get('kees_cookiebar.cookiebar_type');

    if ($cookiebar_type === "0") {
        unset($data['tabs'][0]['kees_cookiebar.config']);
    }
}

/**
 * Implement helper function GetCookieValue()
 *
 * to get the value of the cookie set by this module
 *
 * @return array|string|bool
 */
function GetCookieValue()
{
    $cookie_value = \Drupal::request()->cookies->get($GLOBALS["cookie_name"]);

    if (isJSON($cookie_value)) {
        // For (advanced) cookieblock
        return json_decode($cookie_value, true);
    } else {
        // For (deafult) cookiebar
        return $cookie_value;
    }

    return false;
}

/**
 * Implement helper function isJSON()
 *
 * @param unknown $string
 * @return bool
 */
function isJSON($string) : bool
{
    return is_string($string) && is_array(json_decode($string, true)) ? true : false;
}
